services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=single-node-demo
    ports:
      - "50070:50070"   # Web UI Hadoop 2.x
      - "8020:8020"     # RPC (optionnel pour accès externe)
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./dataset.csv:/dataset/dataset.csv

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=single-node-demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    ports:
      - "50075:50075"   # Web UI DataNode 2.x
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
      - ./dataset.csv:/dataset/dataset.csv

volumes:
  hadoop_namenode:
  hadoop_datanode:
